[package]
name = "loam"
version = "0.1.0"
edition = "2021"

[lints.clippy]
pedantic = "warn"
must_use_candidate = "allow"

[dependencies]
serde = { version = "1.0.195", features = ["derive"] }
serde_json = "1.0.111"
approx = "0.5.1"
